# Create a default ci workflow for the python project
name: CI

on:
  push:
    branches:
      - main      
  pull_request:
    branches:
      - main      

jobs:
    # Checkout the code from the repository
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.2

            # Set up Python 3.12
            - name: Set up Python 3.12
              uses: actions/setup-python@v5.4.0
              with:
                  python-version: 3.12

            # Install dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # Run tests
            - name: Run tests
              run: |
                  pytest tests/



